### ISSUE TITLE
修改: 問題除蟲 - posts/index.json.jbuilder 找不到 user 此方法

### ISSUE THREAD

**Issue by Makoto-Ha** [InfinityRuby/InfinityCode#108]
<img width="629" alt="截圖 2021-06-06 上午10 42 43" src="https://user-images.githubusercontent.com/80435603/120910783-5658b880-c6b4-11eb-94e3-21275663279a.png">
<img width="620" alt="截圖 2021-06-06 上午10 43 26" src="https://user-images.githubusercontent.com/80435603/120910784-58227c00-c6b4-11eb-90c8-ee23dccc4cfe.png">

**Comment by tim32503** [comment]
【問題原因】
經查詢了解問題後，主要是與第二張截圖有關。
因為沒有判斷 `comments` 資料表中是否有該貼文對應之留言，
故導致語法中 `post.comments.first` 結果為 `nil` ，
所以後面的 `user` 無法抓取到資料，才產生錯誤。

【解決方法】
於 `index.json.jbuilder` 檔案中
針對 `comments` 新增判斷條件，確認是否有資料。
