### ISSUE TITLE
修改: API 模組 - 獎勵模組 - 金幣總數讀取 API 錯誤

### ISSUE THREAD

**Issue by tim32503** [InfinityRuby/InfinityCode#110]
![image](https://user-images.githubusercontent.com/16095652/120911577-147f4080-c6bb-11eb-9890-c5f44141df15.png)
➡️ 尚未登入卻直接 call API ，產生驗證失敗的錯誤

![image](https://user-images.githubusercontent.com/16095652/120911639-6fb13300-c6bb-11eb-9806-c59a641018df.png)
➡️ 後端 API 回傳驗證失敗的錯誤訊息，狀態碼 401

進入首頁時因尚未登入，但卻已經 call API 向後端索取資料，故驗證失敗。
請針對驗證失敗做判斷處理，避免產生此錯誤

**Comment by Makoto-Ha** [comment]
這個在最新的那隻PR已經解決了。

**Comment by tim32503** [comment]
@Makoto-Ha 記得是哪支PR嗎? 可以在右側連結PR~
