### ISSUE TITLE
修改: 解題頁面送出答案後，僅呈現 loading 動畫，並無出現答案正確與否的訊息

### ISSUE THREAD

**Issue by shan-0311** [InfinityRuby/InfinityCode#121]
【問題描述】
解題區第一題送出答案後，畫面僅呈現 loading 動畫，並無告知答案是否正確。
![image](https://user-images.githubusercontent.com/16095652/120990652-59869e00-c7b3-11eb-8103-ba8122d730f7.png)

**Comment by tim32503** [comment]
【問題回應】
經了解後，確認系統是有成功將作答紀錄寫進資料庫中，
出錯原因是由於 API 回傳 500 錯誤訊息，導致 loading 動畫持續顯示。
之所以回傳此錯誤訊息，是因為回傳的 JSON 內容有誤，會再加上判斷邏輯去處理錯誤訊息。

![image](https://user-images.githubusercontent.com/16095652/120990855-994d8580-c7b3-11eb-9fe2-cba3a27c897c.png)
