### ISSUE TITLE
修改：解題頁面新增成功率及得金幣

### ISSUE THREAD

**Issue by shan-0311** [InfinityRuby/InfinityCode#131]
新增成功率及得金幣數，排版如下圖
<img width="957" alt="截圖 2021-06-09 下午2 48 43" src="https://user-images.githubusercontent.com/80324554/121306745-ccb61e80-c931-11eb-9a80-af3c09512904.png">

**Comment by Tang-Tou** [comment]
新圖參考
<img width="674" alt="截圖 2021-06-16 下午2 25 01" src="https://user-images.githubusercontent.com/80324554/122168250-a4d53680-ceae-11eb-88fc-d69817fe502f.png">
