### ISSUE TITLE
修改：討論區-調整欄位及新增欄位 placeholder

### ISSUE THREAD

**Issue by shan-0311** [InfinityRuby/InfinityCode#161]
1. 待開發、Most Votes、reset要拔除
<img width="994" alt="截圖 2021-06-09 下午3 35 42" src="https://user-images.githubusercontent.com/80324554/121312843-5cf76200-c938-11eb-8cdb-c8d70bc51bee.png">
2. 調整新增文章字樣

[加號使用這個 icon](https://fontawesome.com/v5.15/icons/plus-square?style=regular)
色碼為 `text-yellow-500`
<img width="772" alt="截圖 2021-06-09 下午3 40 10" src="https://user-images.githubusercontent.com/80324554/121313459-fc1c5980-c938-11eb-8507-626f4c043480.png">

3. 新增 placeholder
<img width="726" alt="截圖 2021-06-09 下午3 45 29" src="https://user-images.githubusercontent.com/80324554/121314231-ba3fe300-c939-11eb-956f-fa2184341cc3.png">

4. 英文字的部分請都改成中文
<img width="965" alt="截圖 2021-06-09 下午3 49 47" src="https://user-images.githubusercontent.com/80324554/121314823-54079000-c93a-11eb-8e85-5505fe7f8cd9.png">

**Comment by Tang-Tou** [comment]
1, 3, 4 已完成
2 待處理
