### ISSUE TITLE
修改：新增文章-版面調整

### ISSUE THREAD

**Issue by shan-0311** [InfinityRuby/InfinityCode#163]
上面的標題欄位和導覽列距離太近，在欄位前加上 ”文章標題“
<img width="1133" alt="截圖 2021-06-09 下午3 46 47" src="https://user-images.githubusercontent.com/80436345/121314492-fa9f6100-c939-11eb-9717-ee07d6eccd2c.png">

按鈕壓到footer，把外框線拿掉
<img width="1127" alt="截圖 2021-06-09 下午3 46 57" src="https://user-images.githubusercontent.com/80436345/121314512-ff641500-c939-11eb-8890-1b14f09461b4.png">

**Comment by tim32503** [comment]
@shan-0311 @Makoto-Ha 
文章編輯器的按鈕本身就已經有氣泡提示了

為什麼還要另外加呢?

**Comment by shan-0311** [comment]
我發現了
已刪除
