### ISSUE TITLE
最新進度dev裡的上傳頭像功能噴錯

### ISSUE THREAD

**Issue by Makoto-Ha** [InfinityRuby/InfinityCode#186]
<img width="1783" alt="截圖 2021-06-11 下午6 00 15" src="https://user-images.githubusercontent.com/80435603/121669519-f82a3c00-cade-11eb-8782-5ba9ff3db0ed.png">

**Comment by Tang-Tou** [comment]
有更新 key 嗎～～～～

**Comment by Makoto-Ha** [comment]
哪裡有key，i need!
