### ISSUE TITLE
修改: 討論區及解題區未設權限

### ISSUE THREAD

**Issue by Tang-Tou** [InfinityRuby/InfinityCode#195]
未登入者輸入網址也可進討論區及解題區，請設權限及調整 API

**Comment by Tang-Tou** [comment]
`/api/v1/users/1/completed_rate` 這隻也需要設權限
<img width="677" alt="截圖 2021-06-13 下午2 45 53" src="https://user-images.githubusercontent.com/80324554/121797961-11092d80-cc56-11eb-8bdf-733dbb517246.png">

**Comment by Tang-Tou** [comment]
`/api/v1/users/1/completed_rate` 用判斷式處理好了

**Comment by Makoto-Ha** [comment]
good
