### ISSUE TITLE
最新dev的chart.js不管切到哪都會噴錯

### ISSUE THREAD

**Issue by Makoto-Ha** [InfinityRuby/InfinityCode#198]
<img width="683" alt="截圖 2021-06-12 下午4 28 05" src="https://user-images.githubusercontent.com/80435603/121770329-4ac92e00-cb9b-11eb-97fa-37c1a0207b86.png">

**Comment by Tang-Tou** [comment]
已處理了！

**Comment by Makoto-Ha** [comment]
了解
