### ISSUE TITLE
修改: 導覽列金幣數量錯誤

### ISSUE THREAD

**Issue by tim32503** [InfinityRuby/InfinityCode#200]
![image](https://user-images.githubusercontent.com/16095652/121774029-7e638280-cbb2-11eb-90ad-2cd8eff2e802.png)
上圖導覽列顯示金幣數量為 5

![image](https://user-images.githubusercontent.com/16095652/121774147-73f5b880-cbb3-11eb-9077-7a515949414a.png)
透過 Rails console 查詢的話 金幣數量則為 70

**Comment by Makoto-Ha** [comment]
這個目前等以庭的chart.js修正後，這個就不會有金幣顯示錯誤的問題在了。
