### ISSUE TITLE
修改: 使用者登出後會出現 Routing Error

### ISSUE THREAD

**Issue by Makoto-Ha** [InfinityRuby/InfinityCode#203]
<img width="648" alt="截圖 2021-06-13 上午11 56 29" src="https://user-images.githubusercontent.com/80435603/121794885-a8fb1d00-cc3e-11eb-8db9-8efe5257d308.png">
這邊之前有講到，我是用.catch後直接轉址。
假如我把轉址拿掉後，這邊確實會讓使用者登出，但就是不知道為什麼會出現這個錯誤。

**Comment by Tang-Tou** [comment]
這個還有噴錯嗎？

**Comment by Makoto-Ha** [comment]
會
