### ISSUE TITLE
修改：解題區列表篩選區

### ISSUE THREAD

**Issue by Tang-Tou** [InfinityRuby/InfinityCode#245]
來自 Debby 的建議
1. 最上面點擊篩選程度 radio ，滑鼠應該是變成 pointer
<img width="395" alt="截圖 2021-06-15 下午8 21 51" src="https://user-images.githubusercontent.com/80324554/122051572-54f76080-ce17-11eb-9268-50e51e7db340.png">

**Comment by Makoto-Ha** [comment]
你是說checkbox換成radio? 然後加上pointer?

**Comment by Tang-Tou** [comment]
滑鼠移到勾選處要是 `cursor-pointer` 的效果

**Comment by Makoto-Ha** [comment]
那radio是？

**Comment by Tang-Tou** [comment]
Debby 應該以為我們是用 `radio`，我直接複製貼上的沒注意到，我們是使用 `checkbox`，所以 `radio` 不用理會

**Comment by Makoto-Ha** [comment]
了解，就只是加上pointer這樣

**Comment by Tang-Tou** [comment]
對的～～～
