### ISSUE TITLE
修改：文章單篇頁面按鈕顏色

### ISSUE THREAD

**Issue by Tang-Tou** [InfinityRuby/InfinityCode#247]
來自 Debby 建議
1. 分頁 1 改成深灰色 `gray-500`
2. 送出鈕改成橘底白字 `yellow-500`
<img width="778" alt="截圖 2021-06-15 下午8 27 30" src="https://user-images.githubusercontent.com/80324554/122052302-1dd57f00-ce18-11eb-9cee-ad558ad1d03e.png">

**Comment by Makoto-Ha** [comment]
單篇頁面的分頁1是什麼意思?

**Comment by Tang-Tou** [comment]
<img width="48" alt="截圖 2021-06-15 下午8 56 57" src="https://user-images.githubusercontent.com/80324554/122056509-3a73b600-ce1c-11eb-9e35-01b89ac4044b.png">

**Comment by Makoto-Ha** [comment]
發現送出改橘底白字超怪

**Comment by Tang-Tou** [comment]
上圖看看
