### ISSUE TITLE
修改：Read.me 內容

### ISSUE THREAD

**Issue by Tang-Tou** [InfinityRuby/InfinityCode#252]
放 logo 圖？
版本資訊

yarn install
bundle install
brew install imagemagick 
成員資訊

**Comment by tim32503** [comment]
嗯...這我想看看可以怎麼寫

**Comment by Tang-Tou** [comment]
@tim32503  我先寫這樣，你要改再改

<img width="179" alt="截圖 2021-06-17 上午1 39 18" src="https://user-images.githubusercontent.com/80324554/122266863-d7158100-cf0c-11eb-8b98-e7571db2c215.png">

# 無限解碼戰

網站連結：https://www.infinitycode.online/

### 無限解碼戰讓寫 code 不再是挑戰! Let’s code it!
・ 線上解題 - 由簡單到困難,刷題練習循序漸進
・ 提示功能 - 貼心提示功能讓你不再卡關卡到天荒地老
・ 社群論壇 - 資訊互通有無,提問發表交流樣樣通
・ 匿名發文 - 覺得害羞嗎?匿名發文讓你勇敢發文
・ 排行榜 - 排名及積分成績表,激發使用者的好強心
・ 獎勵成就 - 透過金幣、獎章獎勵制度獲得及時回饋,促進耐玩性、娛樂性

# 版本
ruby '3.0.1'
rails '6.1.3.2'
pg '1.1'

# 安裝流程
```
$ yarn install
$ bundle install
$ brew install imagemagick
```

# 團隊成員

[薛承顥](github_repo)
[黃威誠](github_repo)
[湯家熏](github_repo)
[徐珮珊](github_repo)
[唐以庭](github_repo)
