### ISSUE TITLE
修改 - 會員模組 - 個人資料頁面 - 路徑修改

### ISSUE THREAD

**Issue by tim32503** [InfinityRuby/InfinityCode#72]
修改原因：
個人資料頁面路徑會呈現如下圖的格式
![image](https://user-images.githubusercontent.com/16095652/120089963-7c6cde80-c131-11eb-9d44-26ef0be98869.png)

建議修改方式：
可調整 `routes.rb` 裡面 `user` 和 `profile` 的關聯，目前為各自獨立。
![image](https://user-images.githubusercontent.com/16095652/120090224-724bdf80-c133-11eb-80f8-9985442e46fe.png)

**Comment by Tang-Tou** [comment]
最新的 `development` 已經解決這個問題了，可以再確認一次看看
